export enum ActionsTypes {
    REQUEST_POST_COMMENT= "REQUEST_POST_COMMENT",
    REQUEST_POST_COMMENT_SUCCESS = "REQUEST_POST_COMMENT_SUCCESS",
    REQUEST_POST_COMMENT_ERROR = "REQUEST_POST_COMMENT_ERROR",
    SET_LOADING_POST_COMMENT = "SET_LOADING_POST_COMMENT",
  }
  