export enum ActionsTypes {
  SET_COMMENT_REACTION = "SET_COMMENT_REACTION",
  COMMENT_REACTION_COUNT_PLUS = "COMMENT_REACTION_COUNT_PLUS",
  COMMENT_REACTION_COUNT_MINUS = "COMMENT_REACTION_COUNT_MINUS",
}
