export enum ActionsTypes {
  REQUEST_ADD_COMMENT_REACTION = "REQUEST_ADD_COMMENT_REACTION",
  REQUEST_UPDATE_COMMENT_REACTION = "REQUEST_UPDATE_COMMENT_REACTION",
  REQUEST_REMOVE_COMMENT_REACTION = "REQUEST_REMOVE_COMMENT_REACTION",
}
