export enum ActionsTypes {
  SET_ANNOUNCEMENT_DATA = "SET_ANNOUNCEMENT_DATA",
  REQUEST_ANNOUNCEMENTS = "REQUEST_ANNOUNCEMENTS",
  REQUEST_ANNOUNCEMENT_SUCCESS = "REQUEST_ANNOUNCEMENT_SUCCESS",
  REQUEST_ANNOUNCEMENT_ERROR = "REQUEST_ANNOUNCEMENT_ERROR",
  SET_LOADING_ANNOUNCEMENT = "SET_LOADING_ANNOUNCEMENT",
}
