export enum ActionsTypes {
  SET_ANNOUNCEMENT_DATA = "SET_ANNOUNCEMENT_DATA",
  REQUEST_ANNOUNCEMENTS = "REQUEST_ANNOUNCEMENTS",
  REQUEST_ANNOUNCEMENT_SUCCESS = "REQUEST_ANNOUNCEMENT_SUCCESS",
  REQUEST_ANNOUNCEMENT_ERROR = "REQUEST_ANNOUNCEMENT_ERROR",
  SET_LOADING_ANNOUNCEMENT = "SET_LOADING_ANNOUNCEMENT",
  SET_CURRENT_PAGE = "SET_CURRENT_PAGE",
  SET_LOADING_MORE = "SET_LOADING_MORE",
  EMPTY_ANNOUCNEMENT_DATA = "EMPTY_ANNOUCNEMENT_DATA",
  SET_SUBMIT_POST_CLICKED = "SET_SUBMIT_POST_CLICKED",
}
