export enum ActionsTypes {
  REQUEST_ANNOUNCEMENT = "REQUEST_ANNOUNCEMENT",
  REQUEST_ANNOUNCEMENT_SUCCESS = "REQUEST_ANNOUNCEMENT_SUCCESS",
  REQUEST_ANNOUNCEMENT_ERROR = "REQUEST_ANNOUNCEMENT_ERROR",
}
