export enum ActionsTypes {
  REQUEST_CHECK_ID = "REQUEST_CHECK_ID",
  REQUEST_CHECK_ID_SUCCESS = "REQUEST_CHECK_ID_SUCCESS",
  REQUEST_CHECK_ID_ERROR = "REQUEST_CHECK_ID_ERROR",
  SET_CHECK_ID_SUCCESS = "SET_CHECK_ID_SUCCESS",
}

export enum SubTitle {
  SIGN_UP = "Sign Up",
}
