export enum ActionsTypes {
  SET_SIGN_IN_DATA = "SET_SIGN_IN_DATA",
  REQUEST_SIGN_IN = "REQUEST_SIGN_IN",
  REQUEST_SIGN_IN_SUCCESS = "REQUEST_SIGN_IN_SUCCESS",
  REQUEST_SIGN_IN_ERROR = "REQUEST_SIGN_IN_ERROR",
  SET_VERIFICATION_ERROR = "SET_VERIFICATION_ERROR",
  SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE",
}
