export enum ActionsTypes {
  SET_POST_REACTION = "SET_POST_REACTION",
  POST_REACTION_COUNT_PLUS = "POST_REACTION_COUNT_PLUS",
  POST_REACTION_COUNT_MINUS = "POST_REACTION_COUNT_MINUS",
  //AS
  SET_POST_COMMENT_COUNT = "SET_POST_COMMENT_COUNT",
  REQUEST_POST_COMMENT_COUNT= "REQUEST_POST_COMMENT_COUNT",
  REQUEST_POST_COMMENT_COUNT_SUCCESS = "REQUEST_POST_COMMENT_COUNT_SUCCESS",
  REQUEST_POST_COMMENT_COUNT_ERROR = "REQUEST_POST_COMMENT_COUNT_ERROR",
  SET_LOADING_POST_COMMENT_COUNT = "SET_LOADING_POST_COMMENT_COUNT"
}
