export enum ActionsTypes {
  REQUEST_ADD_ANNOUNCEMENT_REACTION = "REQUEST_ADD_ANNOUNCEMENT_REACTION",
  REQUEST_UPDATE_ANNOUNCEMENT_REACTION = "REQUEST_UPDATE_ANNOUNCEMENT_REACTION",
  REQUEST_REMOVE_ANNOUNCEMENT_REACTION = "REQUEST_REMOVE_ANNOUNCEMENT_REACTION",
}
